# Gradle
org.gradle.jvmargs=-Xmx8G

# Minecraft / Loader
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_version=0.140.0+1.21.11

# Mod
mod_version=1.21.11-0.9
maven_group=com.blocklegend001
archives_base_name=OnlyExcavators

# Dependencies
rei_version=20.0.811